# Generated by Django 3.1.1 on 2020-10-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_push_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_data', models.JSONField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummy_push_service.website')),
            ],
        ),
    ]
